### ISSUE TITLE
Tor not TOR

### ISSUE THREAD

**Issue by grrrrr** [AirVPN/airvpn-client#21]
Being pedantic though the correct writing is `Tor` not `TOR`

https://www.torproject.org/docs/faq.html.en#WhyCalledTor

[Messages.cs#L138](https://github.com/AirVPN/airvpn-client/blob/1462c1265365c51036d1d8489220950d1dc8a80d/src/Core/Messages.cs#L138) and [Messages.cs#L139](https://github.com/AirVPN/airvpn-client/blob/1462c1265365c51036d1d8489220950d1dc8a80d/src/Core/Messages.cs#L139) should be updated to show correct written

TOR is also written in other place but not visible to end user so you choice for changing

**Comment by AirVPN** [comment]
Absolutely right. Fixed in all places with the latest commit.
