### ISSUE TITLE
update .deb package dependencies for Ubuntu 16.04

### ISSUE THREAD

**Issue by johnnagro** [AirVPN/airvpn-client#31]
Ubuntu 16.04 is the new LTS. The current deb won't cleanly install with the existing dependencies (at least not on my machine). I was able to modify the deb to update the dependencies based on the currently available apt packages.

existing deb package dependencies are:

`Depends: gksu, mono-runtime, mono-utils, libmono-system-runtime2.0-cil, libmono-winforms2.0-cil, libmono-corlib2.0-cil, openvpn, stunnel4`

modified deb package dependencies to make it cleanly install on Ubuntu 16.04:

`Depends: gksu, mono-runtime, mono-utils, libmono-system-runtime4.0-cil, libmono-system-windows-forms4.0-cil, libmono-corlib4.5-cil, openvpn, stunnel4`

**Comment by amnesiac-kid** [comment]
I've got the same problem.

**Comment by johnnagro** [comment]
@amnesiac-kid for a work-around:

1. download the official airvpn .deb package from here https://airvpn.org/linux/
2. then I used [this script](https://gist.github.com/johnnagro/e7e8a756bff60c94083a175087cbcd73) to change the dependencies to the ones i listed in the ticket. 
3. Then i apt installed the dependencies `sudo apt install gksu, mono-runtime, mono-utils, libmono-system-runtime4.0-cil, libmono-system-windows-forms4.0-cil, libmono-corlib4.5-cil, openvpn, stunnel4`
4. and then installed the airvpn package `dpkg -i airvpn_linux_x64_debian.deb`

**Comment by amnesiac-kid** [comment]
Thank you @johnnagro for your help. I know that this way you described works. I got it working yesterday with another method by following the advice of one of the staff members on the airvpn forum. You can just download the portable linux version of airvpn, the one without mono and it works in Ubuntu too. Anyway, I'm glad it works for both of us now and thank your for your help nevertheless.

**Comment by johnnagro** [comment]
@amnesiac-kid

**Comment by johnnagro** [comment]
@amnesiac-kid glad you got it all figured out!

**Comment by w3techie** [comment]
Here is what I used from strykenKN:

[https://airvpn.org/topic/17180-ubuntu-1604-airvpn-client-installation-missing-dependencies/](url)

> Please install the following on the console:
 
`sudo` apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys `3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF`
`echo` "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee `/etc/apt/sources.list.d/mono-xamarin.list`
`sudo` apt-get update

> and then the following are running:
 
`sudo` apt-get install mono-complete

> then can AirVPN completely install

**Comment by w3techie** [comment]
I actually had to use `alien` on the RPM package to get it working on Bodhi, a Ubuntu-derived distro. It might be interesting to compare the results from `alien` to the original package?
