### ISSUE TITLE
 Checking login ..., 1° try failed (The request timed out) error

### ISSUE THREAD

**Issue by Baccount** [AirVPN/airvpn-client#49]
Every time I try to login to Eddie on my MacBook Pro I get Checking login ..., 1° try failed (The request timed out) error, this happens until it times out. My MacBook works with no problems running the exact same version of Eddie and Mac OS. I've reinstalled Mac OS Sierra on my MacBook Pro and I still get the same error, I'm on the same Wi-Fi network and this only happens on my MacBook Pro. Also when I move Eddie to the applications folder I get the same error every time. All other VPN clients work properly, including tunnelBlick, viscosity. I've also make sure my firewall is disabled. Here are my logs, air VPN support has not been able to fix the issue here is their response.

Hello!

Since the problem is not reproducible we are unable to help you, unfortunately.

Kind regards
AirVPN Support Team
[Eddie_20170125_225204.txt](https://github.com/AirVPN/airvpn-client/files/731672/Eddie_20170125_225204.txt)

**Comment by supermensa** [comment]
I'm experiencing this problem as well on Mac OS Sierra & Macbook Pro.

**Comment by Baccount** [comment]
It doesn't look like a developer response to these messages. I'm not sure if this issue will be fixed.

**Comment by supermensa** [comment]
I'll try the support forum
[https://airvpn.org/forum/3-eddie-airvpn-client/](https://airvpn.org/forum/3-eddie-airvpn-client/)

**Comment by Baccount** [comment]
I have tried to support for many times I've talk to their support team and the issue has not been resolved.  Your best bet is just to use tunnelblick because AIrvpn and is unable to fix it.

**Comment by Baccount** [comment]
It looks like the developer fixed the issue in the latest beta! just install the latest experimental build.
https://airvpn.org/macosx/

**Comment by Clodo76** [comment]
This issue it's fixed also in the latest stable. Sorry about the delay, but normally it's the support forum the right place about issues.

**Comment by freediverx** [comment]
1) This issue has not been fixed.
2) There is no "experimental beta" available for download.
3) Using Tunnelblick is NOT an acceptable workaround.
4) The Support Forum has not offered any assistance.
